# Generated by Django 4.2.7 on 2023-11-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_subscibers_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscibers',
        ),
    ]
